# Generated by Django 2.2.13 on 2022-01-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='primary_image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='secondary_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
